global:
  pre_a_selected: 
    - 5.0
    - 10.0
    - 25.0
    - 50.0
    - 100.0
  pre_frame_rate:
    - 24.0
    - 12.0
    - 6.0 
    - 1.0
  pre_bitrate:
    - 1000.0
    - 500.0 
    - 100.0
    - 10.0
  database_ip: 'localhost'
  database_port: 8086
  database_name: 'merge_storage'
  base_path: '/home/min/Multi-level-Feature-Driven-Storage-Server'
  storage_path: 'storage_server_volume/SmartPole/Pole1'
  converted_storage_path: 'storage_server_volume/converted'

  camera2SLE: 5000
  SLE2AP: 7000
  SLE2camera: 6000

  agent2DDM: 5001
  DDM2DP: 7001
  DP2agent: 6001

dispatcher:
  SLE_trigger_time: 6 # hour 


SLE:
  algo: EXP # use which algo to in SLE to decide the sample length, EX
  # delta_i: 300

DDM:
  algo: None

EXP:
  PHASE: SLE # experiments for SLE
  S_MONTH: 11
  E_MONTH: 11
  S_DAY: 16
  E_DAY: 17 


db_agent:
  DDM_threshold: 5120



